name: Build and Publish to PyPI

on:
  release:
    types: [published] 

permissions:
  contents: read
  id-token: write  

jobs:
  release-build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" 

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          python -m pip install build  # Install the build module

      - name: Build distribution
        run: python -m build 

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/  

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build 

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/ 

      - name: Install Twine
        run: pip install twine 

      - name: Publish distribution to PyPI
        env:
          TWINE_USERNAME: __token__ 
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  
        run: twine upload dist/*
